### ISSUE TITLE
Constructing a service which has a dependency which has parameters?

### ISSUE THREAD

**Issue by Kasheen** [gracicot/kangaru#100]
I'm wondering if it's possible to use the container to construct a service which depends on another service which in turn requires parameters.

Example:

````c++
class TypeA
{
	QString mParam;
	
public:
	explicit TypeA(const QString &param) : mParam(param) {}
	
	const QString &getParam() const { return mParam; }
};

class TypeB
{
	const TypeA &mTypeA;
	
public:
	explicit TypeB(const TypeA &typeA) : mTypeA(typeA) {}
	
	const QString &getTypeAParam() const { return mTypeA.getParam(); }
};

struct TypeAService : kgr::service<TypeA> {};
struct TypeBService : kgr::service<TypeB, kgr::dependency<TypeAService>> {};

int main(int argc, char *argv[])
{
	kgr::container container;
	
	container.service<TypeAService>("a"); // Good
	container.service<TypeBService>("a"); // Bad - Is there any way to pass the parameter to the TypeA dep?
	
	return 1;
}
````

I see it's possible to pass parameters to a non-single service, but in the docs any service which then depends on that service requires the initial service to be set up with a default value. (For instance in the docs the `SceneService` has parameters, but when it's used by the `ScreenService` it uses its default values.)

Is this somehow possible via a custom service definition? I think that in my use-case it might even be alright if the value can be hard-coded at compile time. In my use case I have many different types like `TypeC`, `TypeD`, `TypeE` etc which all depend on `TypeA`, but they require `TypeA` to have a different value passed.

I looked at custom service definitions but the docs only show how to pass parameters to the top level service, not any of its dependencies.

Thanks for any help!

**Comment by gracicot** [comment]
For that to work you will need `TypeA` to be a single service, or indeed a custom service.

This is because sending the parameters for `TypeA` when constructing `TypeB` each time kind of break the point of automatic injection, since you would have to know about `TypeA` when constructing `TypeB`. At that point, I would simply send the `TypeA` explicitly.

But single service do allow for parameters to be injected. You only need to mark `TypeA` to be supplied. That tells the container to stop trying to construct it and wait for you to construct it with parameters:

```c++
struct TypeAService : kgr::single_service<TypeA>, kgr::supplied {};
struct TypeBService : kgr::service<TypeB, kgr::dependency<TypeAService>> {};

int main(int argc, char *argv[])
{
	kgr::container container;
	
	container.emplace<TypeAService>("a"); // Good
	container.service<TypeBService>(); // Still okay, use the `TypeA` we emplaced with its parameters
	
	return 0;
}
```
I cover this feature here: [05. Supplied Services](https://github.com/gracicot/kangaru/wiki/05.-Supplied-Services)

---

A custom service definition will enable you to pass the parameters, but usually in a fixed way, or in a way that depends on another service. Doing that is usually more complicated than it needs to be, but the functionality is there in case you need it. It gives you nearly full control over the injection process and how you construct your types.

A custom service would look like this:

```c++
struct TypeAService {
    TypeAService(kgr::in_place_t, QString const& str) : instance{str} {}
    
    static auto construct() -> kgr::inject_result<>
    {
        return kgr::inject(QString{"a"});
    }
    
    auto forward() -> TypeA {
        return std::move(instance);
    }
    
private:
    TypeA instance;
};
```

As you can see, it will inject the `QString{"a"}` into the `TypeAService` so you can send them to the constructor. This also allow you to get services inside the `construct` function in order to compute what parameters should be sent. I usually don't like doing that since it looks more implicit, but it's there.

**Comment by Kasheen** [comment]
Thank you for the reply.

I think you're right about the parameters of `TypeA` making the automatic injection into `TypeB` less useful, I hadn't considered that at this point I would might as well be passing `TypeA` explicitly when constructing `TypeBService` using the container.

All of your suggestions seem good though - I can just make a service(s) or single service for `TypeA` which fixes its parameters via emplace or custom definition before using it in my other types. I'm thinking also I might be able to use the named mappings to help inject the different specialised `TypeAService`s into where they are needed.

Thanks again. Just wanted to check that there wasn't some other way to do this, I'll close the issue since it seems answered.

**Comment by gracicot** [comment]
My pleasure! Also, to have multiple `TypeAService`, you can fork the container using `container.fork()`. It returns a container that act just like the original, except that you can emplace service to be available only to that container.

You could use that to fork the context of your application:

```c++
auto container = kgr::container{};
auto fork1 = container.fork(); // inherits all service from container
auto fork2 = container.fork(); // this one too

fork1.emplace<TypeAService>("a"); // add TypeA
fork2.emplace<TypeAService>("b"); // add TypeA too, independent form fork1
```

So you can have different "sub context" or "sub container" for different places in your code.

I hope it helps! If you need anything else don't hesitate to open another issue or reach me on gitter to chat!
