### ISSUE TITLE
Bit defender marking exe as malware

### ISSUE THREAD

**Issue by TheBossBaby** [gracicot/kangaru#107]
I am working on a game using c++ and kangaru on Visual Studio.
So when I compile the source code it creates a debug exe file & runs it.
Bit defender is marking the exe file as malware

**Comment by gracicot** [comment]
Hey @TheBossBaby

Thanks for reaching out. I will need a minimal source code that (preferably in a small single file) reproduce the issue for me to analyse what could be the cause. It may or may not be kangaru's fault.

**Comment by gracicot** [comment]
Hi @TheBossBaby . I will assume this issue is either not reproducible and you don't have the issue anymore. I was not able to reproduce the issue on multiple machine and you haven't provided anything that would allow me to identify the problem. Complain to the bit defender team, as it's probably an issue on their side.
