### ISSUE TITLE
Use more advanced techniques for autowire detection

### ISSUE THREAD

**Issue by JeWe37** [gracicot/kangaru#112]
**Is your feature request related to a problem? Please describe.**
Current autowire is both somewhat slow as #79 explains and by default limited in the number of dependencies. 

**Describe the solution you'd like**
There's a few techniques around, notably the type loophole and structured binding based detection, that could be helpful in speeding up the detection and removing that limitation.

**Describe alternatives you've considered**
The current option has the advantage of being neither limited to aggregates nor technically a defect.

**Additional context**
These techniques are implemented for instance in [Boost PFR](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_pfr/limitations_and_configuration.html). Especially the type loophole is, uhh, a bit of a brain teaser conceptually. So it might not be easy to implement.

**Comment by gracicot** [comment]
Hmm, I'm no so sure about how those techniques would help. They work pretty well to guess the amount of members in an aggregate, but fails for any other types.

As for detecting the amount of parameter, what I want is to take the constructor that takes the most parameters (including defaulted parameters), whereas loophole based always takes the shortest while avoiding special constructors. I'm not sure how to do that without limiting the amount of parameters. I limited it to 8 because it seemed like a big amount of dependencies, and I wanted to be fast enough.

For the speed, I don't think that benchmark was really good. When defining the service map, you should be using friend functions. It will not get slowed as you add more services that way. Granted, the whole library is quite slow at the moment. 5.x.y Is much much faster.

**Comment by JeWe37** [comment]
Hmmm, I see. I guess without having a limit you'll necessarily run into infinite recursion issues when attempting to detect further constructors. I do think it might be able to avoid being exponential in compile-time complexity in the number of constructor parameters though? You should be able to detect the types, just not the constructor length.

**Comment by gracicot** [comment]
Oh! Yes, totally valid concern. It will require more advanced techniques, like doing a first pass to detect the number of parameter, then extract the types to see if it can be injected, then continue with the next smaller number of parameter if it can't.

This is actually how I do it in kangaru 5 now, but there's still quite of a long way to go since it's a complete rewrite in C++20. There is significant compile time improvements to the point that all probably shave off a minute or two when compiling my game engine.

**Comment by JeWe37** [comment]
Alright then I guess then this can be closed, thanks for the info!

**Comment by gracicot** [comment]
And thanks for the report :)
