### ISSUE TITLE
Using classes -> "cannot instantiate abstract class"

### ISSUE THREAD

**Issue by MJLHThomassen-Sorama** [gracicot/kangaru#74]
Hi there,

I am currently evaluating several c++ iot containers and came across your project. I'm building a demo app with our current codebase to see how kangaru can be implemented.

Currently, all our classes follow a C#-ish design pattern, that is, a class ISomething abstract class as interface, then a class SomethingImplementation : ISomething inheriting from that.

Using kangagu, i get a compile error for the following bit of code:

```
class ISomething
{
public:
    virtual void someFuction() = 0;
}

class SomethingImplementation : public ISomething
{
public:
    void someFunction() override
    {
        // Stuff here
    }
}

struct ISomethingService:
	kgr::abstract_service<ISomething>,
	kgr::defaults_to<struct SomethingImplementationService> {};

struct SomethingImplementationService:
	kgr::single_service<SomethingImplementation>,
	kgr::overrides<ISomethingService> {};

void main()
{
	kgr::container container;

        // Exepect to get a "SomethingImplementation" instance here
	auto something = container.service<ISomethingService>();
}
```

However, when I compile, i get the following error:

error C2259: 'ISomething': cannot instantiate abstract class.

When i compile and run your Example 3, which is the same, it does work. What am I doing wrong?

**Comment by gracicot** [comment]
Hi MJLHThomassen-Sorama,

I just tried your code. I fixed the missing semicolon, the void main to int main, and the name in your interface. Then I got the same error as you.

This is because abstract services inject by reference by default. `auto something = ...` will try to make a copy of the abstract class, into a new instance of it, which is impossible.

Simply replace your last line:
```c++
// Good, reference to an abstract class
auto& something = container.service<ISomethingService>();
```

You can also use service sent by shared pointer, but beware of the overhead and shared ownership:
```c++
struct ISomethingService:
    kgr::abstract_shared_service<ISomething>,
    kgr::defaults_to<struct SomethingImplementationService> {};

struct SomethingImplementationService:
    kgr::shared_service<SomethingImplementation>,
    kgr::overrides<ISomethingService> {};
```

Let me know if your problem is solved!

**Comment by MJLHThomassen-Sorama** [comment]
Hey, thanks for the quick response.

Yeah i quickly "copied and obfucated" the code example, sorry for the typo's there. I will try your solution and get back to you on it, thanks!

**Comment by gracicot** [comment]
Hello again! This question issue has been open and inactive for a while. The presented solution seemed to fix the  problem in the code example posted above.

Unless the problem persist, I'll close this issue and assume the problem is fixed. If the problem indeed persist, please simply reply here.

Thank you again for posting an issue here!
