### ISSUE TITLE
Add test make target

### ISSUE THREAD

**Issue by timofurrer** [gracicot/kangaru#90]
As far as I can tell the tests need to be built separately within the `test/` directory.
Is there a particular reason why not building the tests in the `all` target of the root `make` .. and running them with `make test` ?

**Comment by gracicot** [comment]
It's included by default in the `all` target when running cmake with `-DCMAKE_KANGARU_TEST=ON` (and also C++14 and C++17 specific tests) as argument. I chose that default at the time because most users usually simply want the package and the exported targets, not testing it, which is more usual in a development workflow.

I didn't documented that part yet, maybe that would be useful.

**Comment by gracicot** [comment]
I added documentation for tests in the readme. I'll close this issue for now.
